[package]
name = "test_solana"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
serde = "1.0.217"
serde_json = "1.0.137"
serde_yaml = "0.9.34"
solana-account-decoder-client-types = "2.1.10"
solana-client = "2.1.10"
solana-sdk = "2.1.10"
tokio = "1.43.0"
